import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@days-old/components/ThemeProvider";

const bespokeSans = localFont({
  src: "../public/fonts/BespokeSans-Variable.woff2",
  variable: "--font-bespoke",
});

const crimsonPro = localFont({
  src: [
    { path: "../public/fonts/CrimsonPro-Variable.woff2", style: "normal" },
    {
      path: "../public/fonts/CrimsonPro-VariableItalic.woff2",
      style: "italic",
    },
  ],
  variable: "--font-crimson",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${bespokeSans.variable} ${crimsonPro.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
